name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    # - name: Set up MinGW
    #   uses: egor-tensin/setup-mingw@v2
    #   with:
    #     platform: x64
    - name: Build linux
      run: |
        xmake f --toolchain=clang -y
        xmake -v -y
    # - name: Build windows - mingw64
    #   run: |
    #     #xmake f -p mingw --sdk=/usr/local/i386-mingw32-4.3.0/ -a x86_64 -y
    #     xmake f -p mingw -a x86_64 -y
    #     xmake -v
    - name: Check files
      run: |
        ls -alhR build/
    # - uses: actions/github-script@v7 
    #   with: 
    #     script: |
    #       const releases = await github.rest.repos.listReleases({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #       });
    #       for (const release of releases.data) {
    #         if (release.tag_name === 'develop') {
    #           await github.rest.repos.deleteRelease({
    #             owner: context.repo.owner,
    #             repo: context.repo.repo,
    #             release_id: release.id,
    #           });
    #         }
    #       }
    #       await github.rest.git.deleteRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: `tags/develop`,
    #       });
          
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: develop
        tag_name: develop
        fail_on_unmatched_files: true
        files: build/linux/x86_64/release/*
