name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7 
        with: 
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const release of releases.data) {
              if (release.tag_name === 'develop') {
                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release.id,
                });
              }
            }
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/develop`,
            });

  build:
    needs: build-prefix
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            # name: windows-x86_64
            plat: windows
            arch: x64
          - os: macos-14
            # name: macosx-arm64
            plat: macosx
            arch: arm64
          - os: ubuntu-latest
            # name: linux-x86_64
            plat: linux
            arch: x86_64

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build
      run: |
        #xmake f --toolchain=clang -y
        xmake -v -y

    - name: Test
      run: |
        ./Excel2Config/e2c --help

    - uses: actboy168/action-zip@main
      id: zip
      with:
        name: e2c-${{ matrix.plat }}-${{ matrix.arch }}
        path: |
          Excel2Config/
          
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: develop
        tag_name: develop
        fail_on_unmatched_files: true
        files: ${{  steps.zip.outputs.output }}
